"""
Extension Creator
Creates new extensions from LLM-generated code
"""

import json
from pathlib import Path
from typing import Dict, Any
from datetime import datetime


class ExtensionCreator:
    """Create new extensions"""
    
    def __init__(self):
        self.extensions_dir = Path(__file__).parent / "extensions"
        self.extensions_dir.mkdir(parents=True, exist_ok=True)
    
    def create_extension(
        self,
        intent_name: str,
        generated_code: 'GeneratedCode',
        description: str,
        parameters: Dict[str, Any] = None
    ) -> Optional[str]:
        """
        Create new extension from generated code
        
        Args:
            intent_name: Name of intent (e.g., "download_file")
            generated_code: Code from CodeGenerator
            description: What this extension does
            parameters: Parameter descriptions
            
        Returns:
            The actual intent name used (may have version suffix), or None if failed
        """
        
        if parameters is None:
            parameters = {}
        
        # Create extension directory
        ext_dir = self.extensions_dir / intent_name
        
        if ext_dir.exists():
            print(f"[ExtensionCreator] Warning: Extension '{intent_name}' already exists")
            # Add version suffix
            version = 2
            while (self.extensions_dir / f"{intent_name}_v{version}").exists():
                version += 1
            ext_dir = self.extensions_dir / f"{intent_name}_v{version}"
            intent_name = f"{intent_name}_v{version}"
        
        ext_dir.mkdir(parents=True, exist_ok=True)
        
        try:
            # Create metadata.json
            metadata = {
                "name": intent_name,
                "version": "1.0.0",
                "description": description,
                "author": "Fluffy AI",
                "created": datetime.now().isoformat(),
                "intent": intent_name,
                "patterns": generated_code.patterns if hasattr(generated_code, 'patterns') else [],
                "parameters": parameters,
                "safety_level": "needs_confirmation"
            }
            
            (ext_dir / "metadata.json").write_text(
                json.dumps(metadata, indent=2),
                encoding='utf-8'
            )
            
            # Create __init__.py
            (ext_dir / "__init__.py").write_text(
                f'"""Extension: {intent_name}"""\n',
                encoding='utf-8'
            )
            
            # Create handler.py
            class_name = self._to_class_name(intent_name)
            
            handler_code = f'''"""
{intent_name} Extension - Handler
Auto-generated by Fluffy AI
"""

from typing import Dict, Any

class {class_name}Handler:
    """Handle {intent_name} operations"""
    
{self._indent_code(generated_code.executor_method, 1)}

def get_handler():
    return {class_name}Handler()
'''
            
            (ext_dir / "handler.py").write_text(handler_code, encoding='utf-8')
            
            # Create validator.py
            validator_code = f'''"""
{intent_name} Extension - Validator
Auto-generated by Fluffy AI
"""

from action_validator import ValidationResult, SafetyLevel

class {class_name}Validator:
    """Validate {intent_name} operations"""
    
{self._indent_code(generated_code.validation, 1)}

def get_validator():
    return {class_name}Validator()
'''
            
            (ext_dir / "validator.py").write_text(validator_code, encoding='utf-8')
            
            print(f"[ExtensionCreator] ✓ Created extension: {intent_name}")
            print(f"[ExtensionCreator] Location: {ext_dir}")
            
            return intent_name
            
        except Exception as e:
            print(f"[ExtensionCreator] ✗ Failed to create extension: {e}")
            # Clean up on failure
            if ext_dir.exists():
                import shutil
                shutil.rmtree(ext_dir)
            return None
    
    def _to_class_name(self, intent_name: str) -> str:
        """Convert intent_name to ClassName"""
        # download_file -> DownloadFile
        return ''.join(word.capitalize() for word in intent_name.split('_'))
    
    def _indent_code(self, code: str, levels: int = 1) -> str:
        """Indent code by specified levels, handling escaped newlines if present"""
        if not code:
            return ""
            
        # Handle literal "\n" strings if they weren't unescaped by JSON parser
        code = code.replace("\\n", "\n")
        
        indent = "    " * levels
        lines = code.strip().split('\n')
        return '\n'.join(indent + line if line.strip() else '' for line in lines)
    
    def delete_extension(self, intent_name: str) -> bool:
        """Delete an extension"""
        ext_dir = self.extensions_dir / intent_name
        
        if not ext_dir.exists():
            print(f"[ExtensionCreator] Extension '{intent_name}' not found")
            return False
        
        try:
            import shutil
            shutil.rmtree(ext_dir)
            print(f"[ExtensionCreator] ✓ Deleted extension: {intent_name}")
            return True
        except Exception as e:
            print(f"[ExtensionCreator] ✗ Failed to delete extension: {e}")
            return False


# Global singleton
_extension_creator = None


def get_extension_creator() -> ExtensionCreator:
    """Get or create the global ExtensionCreator instance"""
    global _extension_creator
    if _extension_creator is None:
        _extension_creator = ExtensionCreator()
    return _extension_creator


# Test function
if __name__ == "__main__":
    print("=" * 70)
    print("Extension Creator - Test")
    print("=" * 70)
    
    creator = get_extension_creator()
    
    print(f"\n[Test] Extensions directory: {creator.extensions_dir}")
    
    # Create a mock GeneratedCode object
    class MockGeneratedCode:
        def __init__(self):
            self.patterns = [r"test\s+(.+)"]
            self.executor_method = '''def execute(self, command) -> Dict[str, Any]:
    """Execute test command"""
    return {
        "success": True,
        "message": "Test extension works!",
        "action": "test_complete"
    }'''
            self.validation = '''return ValidationResult(
    is_valid=True,
    safety_level=SafetyLevel.SAFE,
    message="Test is safe"
)'''
    
    print("\n[Test] Creating test extension...")
    success = creator.create_extension(
        intent_name="test_extension",
        generated_code=MockGeneratedCode(),
        description="Test extension for demonstration",
        parameters={"test_param": "A test parameter"}
    )
    
    print(f"\n[Test] Extension creation: {'SUCCESS' if success else 'FAILED'}")
    
    if success:
        test_dir = creator.extensions_dir / "test_extension"
        print(f"\n[Test] Created files:")
        for file in test_dir.iterdir():
            print(f"  - {file.name}")
    
    print("\n" + "=" * 70)
    print("TEST COMPLETE")
    print("=" * 70)
