"""
Extension Creator
Creates new extensions from LLM-generated code — supports Python, HTML, JS.
"""

import json
import shutil
from pathlib import Path
from typing import Dict, Any, Optional
from datetime import datetime


class ExtensionCreator:
    """Create new extensions"""
    
    def __init__(self):
        self.extensions_dir = Path(__file__).parent / "extensions"
        self.extensions_dir.mkdir(parents=True, exist_ok=True)
    
    def create_extension(
        self,
        intent_name: str,
        generated_code: 'GeneratedCode',
        description: str,
        parameters: Dict[str, Any] = None,
        language: str = "python",
        has_ui: bool = False,
        web_ui_files: Optional[dict] = None,
        js_handler: Optional[str] = None
    ) -> Optional[str]:
        """
        Create new extension from generated code.

        Returns the actual intent name used (may have version suffix), or None if failed.
        """
        if parameters is None:
            parameters = {}

        # ── Resolve directory ────────────────────────────────────────────────
        ext_dir = self.extensions_dir / intent_name
        if ext_dir.exists():
            print(f"[ExtensionCreator] Warning: Extension '{intent_name}' already exists")
            version = 2
            while (self.extensions_dir / f"{intent_name}_v{version}").exists():
                version += 1
            intent_name = f"{intent_name}_v{version}"
            ext_dir = self.extensions_dir / intent_name
        ext_dir.mkdir(parents=True, exist_ok=True)

        # ── Assign logo ──────────────────────────────────────────────────
        logo_name = self._assign_logo(intent_name, ext_dir)

        try:
            # ── Metadata ──────────────────────────────────────────────
            metadata = {
                "name": intent_name,
                "version": "1.0.0",
                "description": description,
                "author": "Fluffy AI",
                "created": datetime.now().isoformat(),
                "intent": intent_name,
                "language": language,
                "has_ui": has_ui,
                "logo": logo_name,
                "patterns": generated_code.patterns if hasattr(generated_code, 'patterns') else [],
                "parameters": parameters,
                "safety_level": "needs_confirmation"
            }
            (ext_dir / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding='utf-8')
            (ext_dir / "__init__.py").write_text(f'"""Extension: {intent_name}"""\n', encoding='utf-8')
            
            # ── Python handler + validator (always created as the Python entry point) ──
            class_name = self._to_class_name(intent_name)

            if language == "js" and js_handler:
                # For JS: handler.py wraps node execution
                handler_code = self._make_js_wrapper(class_name, intent_name, js_handler)
                (ext_dir / "handler.js").write_text(js_handler, encoding='utf-8')
            elif "def get_handler" in getattr(generated_code, 'executor_method', ''):
                # New "whole file" format from Phase 9
                handler_code = generated_code.executor_method
                # Ensure it has basic imports if missing
                if "from typing" not in handler_code:
                    handler_code = "from typing import Dict, Any\n" + handler_code
            else:
                # Legacy snippet format
                handler_code = f'''"""
{intent_name} Extension - Handler
Auto-generated by Fluffy AI
"""

from typing import Dict, Any

class {class_name}Handler:
    """Handle {intent_name} operations"""

{self._indent_code(generated_code.executor_method, 1)}

def get_handler():
    return {class_name}Handler()
'''
            (ext_dir / "handler.py").write_text(handler_code, encoding='utf-8')

            # ── Validator ────────────────────────────────────────────────────
            if "def get_validator" in getattr(generated_code, 'validation', ''):
                # New "whole file" format
                validator_code = generated_code.validation
            else:
                validator_code = f'''"""
{intent_name} Extension - Validator
Auto-generated by Fluffy AI
"""

try:
    from action_validator import ValidationResult, SafetyLevel
except ImportError:
    from brain.action_validator import ValidationResult, SafetyLevel

class {class_name}Validator:
    """Validate {intent_name} operations"""

{self._indent_code(generated_code.validation, 1)}

def get_validator():
    return {class_name}Validator()
'''
            (ext_dir / "validator.py").write_text(validator_code, encoding='utf-8')

            # ── Web UI files (if has_ui) ───────────────────────────────────────
            if has_ui and web_ui_files:
                ui_dir = ext_dir / "ui"
                ui_dir.mkdir(exist_ok=True)
                for filename, content in web_ui_files.items():
                    (ui_dir / filename).write_text(content, encoding='utf-8')
                print(f"[ExtensionCreator] ✓ Web UI created ({len(web_ui_files)} files)")
            
            print(f"[ExtensionCreator] ✓ Created extension: {intent_name}")
            print(f"[ExtensionCreator] Location: {ext_dir}")

            # ── Auto-register ──────────────────────────────────────────────────
            try:
                from extension_loader import get_extension_loader
                loader = get_extension_loader()
                # Ensure patterns are a list of strings
                raw_patterns = metadata.get("patterns", [])
                if not isinstance(raw_patterns, list):
                    raw_patterns = [str(raw_patterns)]
                
                clean_patterns = []
                for p in raw_patterns:
                    if isinstance(p, str):
                        clean_patterns.append(p.replace('\\\\', ''))
                    else:
                        clean_patterns.append(str(p))

                registry_metadata = {
                    "name": metadata["name"],
                    "intent": intent_name,
                    "patterns": clean_patterns,
                    "description": description,
                    "directory": ext_dir.name,
                    "created": metadata["created"],
                    "version": metadata["version"],
                    "enabled": True,
                    "language": language,
                    "has_ui": has_ui,
                    "logo": logo_name,
                    "author": metadata.get("author", "Fluffy AI")
                }
                if loader.register_extension(intent_name, registry_metadata):
                    print(f"[ExtensionCreator] ✓ Registered — ready immediately!")
                else:
                    print(f"[ExtensionCreator] ⚠ Registration failed — restart may be needed")
            except Exception as e:
                print(f"[ExtensionCreator] ⚠ Auto-registration failed: {e}")

            return intent_name
            
        except Exception as e:
            import traceback
            print(f"[ExtensionCreator] ✗ Failed to create extension: {e}")
            print(traceback.format_exc())
            # Clean up on failure
            if ext_dir.exists():
                try:
                    import shutil
                    shutil.rmtree(ext_dir)
                except:
                    pass
            return None
    
    def rewrite_handler(self, intent_name: str, new_handler_code: str) -> bool:
        """Rewrite handler.py of an existing extension with new code (for error-healing)."""
        ext_dir = self.extensions_dir / intent_name
        if not ext_dir.exists():
            # Try to find it by scanning
            for d in self.extensions_dir.iterdir():
                if d.is_dir():
                    meta_file = d / "metadata.json"
                    if meta_file.exists():
                        try:
                            meta = json.loads(meta_file.read_text())
                            if meta.get("intent") == intent_name:
                                ext_dir = d
                                break
                        except Exception:
                            pass
        if not ext_dir.exists():
            print(f"[ExtensionCreator] Cannot rewrite: {intent_name} not found")
            return False
        try:
            class_name = self._to_class_name(intent_name)
            # Wrap the method in the class if not already a full module
            if "def get_handler" not in new_handler_code:
                full_code = f'"""{intent_name} Handler — auto-fixed by Fluffy AI"""\n\nfrom typing import Dict, Any\n\nclass {class_name}Handler:\n{self._indent_code(new_handler_code, 1)}\n\ndef get_handler():\n    return {class_name}Handler()\n'
            else:
                full_code = new_handler_code
            (ext_dir / "handler.py").write_text(full_code, encoding="utf-8")
            print(f"[ExtensionCreator] ✓ Rewrote handler for: {intent_name}")
            return True
        except Exception as e:
            print(f"[ExtensionCreator] ✗ Rewrite failed: {e}")
            return False

    def _assign_logo(self, intent_name: str, ext_dir: Path) -> str:
        """Copy a matching SVG icon into the extension dir. Returns filename."""
        keyword_map = {
            "wifi": "network", "network": "network", "bluetooth": "network",
            "file": "file", "folder": "file", "create": "file", "delete": "file",
            "search": "search", "web": "search", "google": "search",
            "app": "app", "open": "app", "close": "app", "launch": "app",
            "system": "system", "shutdown": "system", "restart": "system",
            "download": "download", "zip": "download", "compress": "download",
            "code": "code", "python": "code", "script": "code",
            "music": "media", "video": "media", "play": "media",
            "weather": "weather", "clock": "clock", "time": "clock",
        }
        icons_dir = Path(__file__).parent / "assets" / "extension-icons"
        matched_icon = None
        name_lower = intent_name.lower()
        for keyword, icon_name in keyword_map.items():
            if keyword in name_lower:
                candidate = icons_dir / f"{icon_name}.svg"
                if candidate.exists():
                    matched_icon = candidate
                    break
        if not matched_icon:
            # Phase 9: Ultimate fallback to specified public/logo.png
            project_root = Path(__file__).parent.parent
            public_logo = project_root / "ui" / "tauri" / "public" / "logo.png"
            if public_logo.exists():
                matched_icon = public_logo
            else:
                # Still fallback to SVG default if logo.png is missing
                fluffy_logo = Path(__file__).parent / "assets" / "fluffy-default-logo.svg"
                if fluffy_logo.exists():
                    matched_icon = fluffy_logo
        
        if matched_icon:
            # Determine extension based on source icon
            ext = matched_icon.suffix or ".svg"
            logo_filename = f"logo{ext}"
            dest = ext_dir / logo_filename
            try:
                import shutil
                shutil.copy2(matched_icon, dest)
                return logo_filename
            except Exception:
                pass
        return ""

    def _to_class_name(self, intent_name: str) -> str:
        """Convert snake_case to PascalCase (e.g. 'scan_wifi' -> 'ScanWifi')"""
        return "".join(word.capitalize() for word in intent_name.split("_"))

    def _make_js_wrapper(self, class_name: str, intent_name: str, js_script: str) -> str:
        """Generate a Python handler.py that wraps a Node.js handler.js script."""
        return f'''"""\n{intent_name} Extension - JS Wrapper Handler\nAuto-generated by Fluffy AI\n"""\n\nimport json\nimport subprocess\nfrom pathlib import Path\nfrom typing import Dict, Any\n\nclass {class_name}Handler:\n    """Runs handler.js via Node.js"""\n\n    def execute(self, command) -> Dict[str, Any]:\n        """Execute JS handler"""\n        try:\n            script = Path(__file__).parent / "handler.js"\n            params_json = json.dumps(command.parameters)\n            # Run node and capture output\n            try:\n                result = subprocess.run(\n                    ["node", str(script)],\n                    input=params_json, capture_output=True, text=True, timeout=30\n                )\n            except FileNotFoundError:\n                return {{"success": False, "message": "Node.js not found. Please install Node.js to run JavaScript extensions."}}\n\n            if result.returncode != 0:\n                return {{"success": False, "message": f"JS Error: {{result.stderr.strip()}}"}}\n            \n            try:\n                return json.loads(result.stdout.strip())\n            except json.JSONDecodeError:\n                return {{"success": True, "message": result.stdout.strip()}} # Fallback to raw output if not JSON\n\n        except Exception as e:\n            return {{"success": False, "message": str(e)}}\n\ndef get_handler():\n    return {class_name}Handler()\n'''
    
    def _indent_code(self, code: str, levels: int = 1) -> str:
        """Indent code by specified levels, handling escaped newlines if present"""
        if not code:
            return ""
            
        # Handle literal "\n" strings if they weren't unescaped by JSON parser
        code = code.replace("\\n", "\n")
        
        indent = "    " * levels
        lines = code.strip().split('\n')
        return '\n'.join(indent + line if line.strip() else '' for line in lines)
    
    def delete_extension(self, intent_name: str) -> bool:
        """Delete an extension"""
        ext_dir = self.extensions_dir / intent_name
        
        if not ext_dir.exists():
            print(f"[ExtensionCreator] Extension '{intent_name}' not found")
            return False
        
        try:
            import shutil
            shutil.rmtree(ext_dir)
            print(f"[ExtensionCreator] ✓ Deleted extension: {intent_name}")
            return True
        except Exception as e:
            print(f"[ExtensionCreator] ✗ Failed to delete extension: {e}")
            return False


# Global singleton
_extension_creator = None


def get_extension_creator() -> ExtensionCreator:
    """Get or create the global ExtensionCreator instance"""
    global _extension_creator
    if _extension_creator is None:
        _extension_creator = ExtensionCreator()
    return _extension_creator


# Test function
if __name__ == "__main__":
    print("=" * 70)
    print("Extension Creator - Test")
    print("=" * 70)
    
    creator = get_extension_creator()
    
    print(f"\n[Test] Extensions directory: {creator.extensions_dir}")
    
    # Create a mock GeneratedCode object
    class MockGeneratedCode:
        def __init__(self):
            self.patterns = [r"test\s+(.+)"]
            self.executor_method = '''def execute(self, command) -> Dict[str, Any]:
    """Execute test command"""
    return {
        "success": True,
        "message": "Test extension works!",
        "action": "test_complete"
    }'''
            self.validation = '''return ValidationResult(
    is_valid=True,
    safety_level=SafetyLevel.SAFE,
    message="Test is safe"
)'''
    
    print("\n[Test] Creating test extension...")
    success = creator.create_extension(
        intent_name="test_extension",
        generated_code=MockGeneratedCode(),
        description="Test extension for demonstration",
        parameters={"test_param": "A test parameter"}
    )
    
    print(f"\n[Test] Extension creation: {'SUCCESS' if success else 'FAILED'}")
    
    if success:
        test_dir = creator.extensions_dir / "test_extension"
        print(f"\n[Test] Created files:")
        for file in test_dir.iterdir():
            print(f"  - {file.name}")
    
    print("\n" + "=" * 70)
    print("TEST COMPLETE")
    print("=" * 70)
