"""
PowerPoint PPTX Deliverable Generator
Generates genuine Microsoft PowerPoint (.pptx) presentations using python-pptx.
Supports title slides, content slides, bullet lists, tables, speaker notes, and citations.
"""

from typing import List, Dict, Any, Union
from pathlib import Path

from brain.artifacts.definitions import ArtifactType
from brain.artifacts.requests import ArtifactRequest
from brain.artifacts.models import SlideData, TableData
from brain.artifacts.generators.interface import ArtifactGenerator


class PPTXArtifactGenerator(ArtifactGenerator):
    """
    Generates genuine Office Open XML PowerPoint (.pptx) presentations.
    """

    @property
    def name(self) -> str:
        return "pptx_generator"

    @property
    def supported_types(self) -> List[ArtifactType]:
        return [ArtifactType.PPTX]

    @property
    def is_available(self) -> bool:
        try:
            import pptx
            return True
        except ImportError:
            return False

    def supports(self, artifact_type: ArtifactType) -> bool:
        return artifact_type == ArtifactType.PPTX

    def generate_to_path(self, request: ArtifactRequest, target_path: Path) -> None:
        if not self.is_available:
            raise RuntimeError("python-pptx library is not installed in the local environment.")

        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor

        prs = Presentation()
        # Set 16:9 widescreen dimensions
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        title_text = (request.metadata.title if request.metadata else None) or request.name.replace(".pptx", "").replace("_", " ").title()
        subtitle_text = request.metadata.description if request.metadata else "Generated by Fluffy Assistant"

        # 1. Title Slide (Layout index 0)
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]

        if title:
            title.text = title_text
        if subtitle and subtitle_text:
            subtitle.text = subtitle_text

        # 2. Parse Slide Data from Content
        slides: List[SlideData] = []
        content = request.content

        if isinstance(content, list):
            for item in content:
                if isinstance(item, SlideData):
                    slides.append(item)
                elif isinstance(item, dict):
                    t_data = None
                    if item.get("table") and isinstance(item["table"], dict):
                        t_data = TableData(headers=item["table"].get("headers", []), rows=item["table"].get("rows", []))
                    slides.append(SlideData(
                        title=item.get("title", "Slide"),
                        content=item.get("content", ""),
                        bullet_points=item.get("bullet_points", []),
                        table=t_data,
                        notes=item.get("notes"),
                    ))
        elif isinstance(content, dict):
            if "slides" in content and isinstance(content["slides"], list):
                for s in content["slides"]:
                    t_data = None
                    if s.get("table") and isinstance(s["table"], dict):
                        t_data = TableData(headers=s["table"].get("headers", []), rows=s["table"].get("rows", []))
                    slides.append(SlideData(
                        title=s.get("title", "Slide"),
                        content=s.get("content", ""),
                        bullet_points=s.get("bullet_points", []),
                        table=t_data,
                        notes=s.get("notes"),
                    ))
        elif isinstance(content, str):
            # Split sections into slides
            sections = content.split("\n\n# ")
            for idx, sec in enumerate(sections):
                lines = sec.strip().splitlines()
                s_title = lines[0].replace("#", "").strip() if lines else f"Section {idx + 1}"
                body_lines = [l for l in lines[1:] if not l.startswith("- ")]
                bullets = [l[2:].strip() for l in lines[1:] if l.startswith("- ")]
                slides.append(SlideData(
                    title=s_title,
                    content="\n".join(body_lines),
                    bullet_points=bullets,
                ))

        if not slides:
            slides.append(SlideData(title="Overview", content="Deliverable briefing presentation."))

        # 3. Create Content Slides
        bullet_slide_layout = prs.slide_layouts[1]
        for s_data in slides:
            s = prs.slides.add_slide(bullet_slide_layout)
            if s.shapes.title:
                s.shapes.title.text = s_data.title

            body_shape = s.placeholders[1]
            tf = body_shape.text_frame
            tf.clear()

            if s_data.content:
                p = tf.paragraphs[0]
                p.text = s_data.content
                p.font.size = Pt(20)

            for bp in s_data.bullet_points:
                p = tf.add_paragraph()
                p.text = bp
                p.level = 0
                p.font.size = Pt(18)

            # Insert Table if present
            if s_data.table and (s_data.table.headers or s_data.table.rows):
                rows_count = len(s_data.table.rows) + (1 if s_data.table.headers else 0)
                cols_count = max(len(s_data.table.headers), len(s_data.table.rows[0]) if s_data.table.rows else 1)
                
                table_shape = s.shapes.add_table(
                    rows=rows_count,
                    cols=cols_count,
                    left=Inches(1.0),
                    top=Inches(3.8),
                    width=Inches(11.3),
                    height=Inches(2.5),
                )
                tbl = table_shape.table

                curr_row = 0
                if s_data.table.headers:
                    for col_idx, h in enumerate(s_data.table.headers):
                        cell = tbl.cell(0, col_idx)
                        cell.text = str(h)
                        for p in cell.text_frame.paragraphs:
                            p.font.bold = True
                            p.font.size = Pt(14)
                    curr_row += 1

                for r in s_data.table.rows:
                    for col_idx, val in enumerate(r):
                        if col_idx < cols_count:
                            cell = tbl.cell(curr_row, col_idx)
                            cell.text = str(val)
                            for p in cell.text_frame.paragraphs:
                                p.font.size = Pt(12)
                    curr_row += 1

            # Speaker Notes
            if s_data.notes:
                notes_slide = s.notes_slide
                notes_slide.notes_text_frame.text = s_data.notes

        # 4. Citations & Provenance Slide
        if request.sources:
            src_slide = prs.slides.add_slide(bullet_slide_layout)
            if src_slide.shapes.title:
                src_slide.shapes.title.text = "Sources & Provenance"
            tf = src_slide.placeholders[1].text_frame
            tf.clear()
            for s in request.sources:
                p = tf.add_paragraph()
                p.text = f"• {s}"
                p.font.size = Pt(16)
                p.font.italic = True

        prs.save(str(target_path))
