/**
 * Fluffy Desktop - Theme Catalog
 * 
 * Formal registry of all 15 design paradigm themes + built-in standard themes.
 * Contains metadata, preview tokens, and aesthetic descriptions.
 * Rule: NO emojis. Clean vector/typography only.
 */

import type { ThemeMode } from "../types/ui";
import type { ThemeDefinition } from "./fluffyDark";

export interface WorkbenchThemeItem extends ThemeDefinition {
  id: ThemeMode;
  category: "Core" | "Structural & Raw" | "Tactile & 3D" | "Futuristic & Retro" | "Modern & Editorial";
  bgPreview: string;
  borderPreview: string;
  accentPreview: string;
  textPreview: string;
  tag: string;
}

export const THEME_CATALOG: WorkbenchThemeItem[] = [
  // ── Core Standard Themes ──
  {
    id: "fluffyDark",
    name: "Fluffy Dark",
    category: "Core",
    description: "Industrial dark operational palette with restrained blue accents. Optimized for low-light workstations.",
    isDark: true,
    bgPreview: "#0d1117",
    borderPreview: "#2d3748",
    accentPreview: "#3b82f6",
    textPreview: "#f0f3f6",
    tag: "Standard",
  },
  {
    id: "fluffyLight",
    name: "Fluffy Light",
    category: "Core",
    description: "Crisp studio light mode with high clarity for bright operational environments.",
    isDark: false,
    bgPreview: "#f3f4f6",
    borderPreview: "#cbd5e1",
    accentPreview: "#2563eb",
    textPreview: "#111827",
    tag: "Light",
  },
  {
    id: "highContrast",
    name: "High Contrast",
    category: "Core",
    description: "Maximum visual separation with stark borders and high luminance contrast for accessibility.",
    isDark: true,
    bgPreview: "#000000",
    borderPreview: "#ffffff",
    accentPreview: "#00ffff",
    textPreview: "#ffffff",
    tag: "A11y",
  },

  // ── The 15 Design Paradigm Themes ──
  {
    id: "minimalism",
    name: "1. Minimalism",
    category: "Structural & Raw",
    description: "Ultra-restrained monochrome with deliberate whitespace, hairline borders, and pure typography.",
    isDark: true,
    bgPreview: "#09090b",
    borderPreview: "#272730",
    accentPreview: "#f4f4f5",
    textPreview: "#fafafa",
    tag: "Monochrome",
  },
  {
    id: "maximalism",
    name: "2. Maximalism",
    category: "Modern & Editorial",
    description: "Vibrant high-density chromatic energy with electric magenta, cyan, and layered indigo depth.",
    isDark: true,
    bgPreview: "#0b0818",
    borderPreview: "#4d3a94",
    accentPreview: "#ff007f",
    textPreview: "#ffffff",
    tag: "High Energy",
  },
  {
    id: "glassmorphism",
    name: "3. Glassmorphism",
    category: "Tactile & 3D",
    description: "Frosted specular glass panels, dynamic ambient refraction blur, and crystal border reflections.",
    isDark: true,
    bgPreview: "linear-gradient(135deg, rgba(16,23,42,0.85) 0%, rgba(30,44,76,0.72) 100%)",
    borderPreview: "rgba(255, 255, 255, 0.3)",
    accentPreview: "#38bdf8",
    textPreview: "#f8fafc",
    tag: "Frosted Glass",
  },
  {
    id: "neumorphism",
    name: "4. Neumorphism",
    category: "Tactile & 3D",
    description: "Soft extruded tactile surfaces with balanced dual light/dark drop-shadows on graphite planes.",
    isDark: true,
    bgPreview: "#21252f",
    borderPreview: "#1a1d25",
    accentPreview: "#60a5fa",
    textPreview: "#e2e8f0",
    tag: "Soft Extrusion",
  },
  {
    id: "claymorphism",
    name: "5. Claymorphism",
    category: "Tactile & 3D",
    description: "Rounded volumetric 3D clay aesthetic with generous pill radii, soft inner highlights, and deep shadows.",
    isDark: true,
    bgPreview: "#181b2c",
    borderPreview: "rgba(255, 255, 255, 0.15)",
    accentPreview: "#a78bfa",
    textPreview: "#f8fafc",
    tag: "Volumetric 3D",
  },
  {
    id: "brutalism",
    name: "6. Brutalism",
    category: "Structural & Raw",
    description: "Raw architectural utilitarianism, stark black-and-white contrast, zero border radius, and bold outlines.",
    isDark: true,
    bgPreview: "#050505",
    borderPreview: "#ffffff",
    accentPreview: "#ffffff",
    textPreview: "#ffffff",
    tag: "Raw Grid",
  },
  {
    id: "neoBrutalism",
    name: "7. Neo-Brutalism",
    category: "Structural & Raw",
    description: "Modern neo-brutalist styling with electric neon lime contrast, bold solid borders, and hard offset block shadows.",
    isDark: true,
    bgPreview: "#121316",
    borderPreview: "#e2f952",
    accentPreview: "#e2f952",
    textPreview: "#ffffff",
    tag: "Offset Shadow",
  },
  {
    id: "skeuomorphism",
    name: "8. Skeuomorphism",
    category: "Tactile & 3D",
    description: "Tactile hardware simulation with metallic textures, inner beveled highlights, and brass accents.",
    isDark: true,
    bgPreview: "#1a1c20",
    borderPreview: "#444a57",
    accentPreview: "#d4a24c",
    textPreview: "#f0f2f5",
    tag: "Hardware Tactile",
  },
  {
    id: "flatDesign",
    name: "9. Flat Design",
    category: "Structural & Raw",
    description: "Zero gradients, zero shadows, pure solid geometric color fields, and clean Swiss layout precision.",
    isDark: true,
    bgPreview: "#1e293b",
    borderPreview: "#334155",
    accentPreview: "#0ea5e9",
    textPreview: "#f8fafc",
    tag: "Zero Shadow",
  },
  {
    id: "materialDesign",
    name: "10. Material Design",
    category: "Modern & Editorial",
    description: "Material 3 tonal surface elevations, calibrated elevation shadows, and lavender primary accents.",
    isDark: true,
    bgPreview: "#141218",
    borderPreview: "#49454f",
    accentPreview: "#d0bcff",
    textPreview: "#e6e1e5",
    tag: "Tonal Elevation",
  },
  {
    id: "bentoUi",
    name: "11. Bento UI",
    category: "Modern & Editorial",
    description: "Modular card geometry inspired by precision hardware grids, dark slate graphite, and indigo micro-glows.",
    isDark: true,
    bgPreview: "#090a0f",
    borderPreview: "#272d40",
    accentPreview: "#6366f1",
    textPreview: "#f1f5f9",
    tag: "Modular Grid",
  },
  {
    id: "y2kDesign",
    name: "12. Y2K Design",
    category: "Futuristic & Retro",
    description: "Turn-of-the-millennium cyber aesthetic with electric aqua/cyan, bubblegum hot pink, and metallic sheen.",
    isDark: true,
    bgPreview: "#0a0e17",
    borderPreview: "#00ffff",
    accentPreview: "#ff00a0",
    textPreview: "#e0f7ff",
    tag: "Cyber 2000",
  },
  {
    id: "retroDesign",
    name: "13. Retro Design",
    category: "Futuristic & Retro",
    description: "1980s monochrome CRT terminal ambiance with glowing phosphor green typography and dark matrix panels.",
    isDark: true,
    bgPreview: "#070d07",
    borderPreview: "#265526",
    accentPreview: "#39ff14",
    textPreview: "#39ff14",
    tag: "Phosphor CRT",
  },
  {
    id: "cyberpunk",
    name: "14. Cyberpunk",
    category: "Futuristic & Retro",
    description: "High-tech low-life neon dystopia with obsidian voids, electric cyan, yellow, and laser magenta edges.",
    isDark: true,
    bgPreview: "#040408",
    borderPreview: "#ff0055",
    accentPreview: "#00f0ff",
    textPreview: "#fcee0a",
    tag: "Neon Dystopia",
  },
  {
    id: "editorialDesign",
    name: "15. Editorial Design",
    category: "Modern & Editorial",
    description: "Quiet luxury broadsheet aesthetic with warm charcoal slate, warm parchment text, and terracotta rules.",
    isDark: true,
    bgPreview: "#121215",
    borderPreview: "#383847",
    accentPreview: "#d96547",
    textPreview: "#f4f0e8",
    tag: "Quiet Luxury",
  },
];
