"""
Knowledge Document and Chunk Domain Entities
Defines entities for parsed content, structured chunks, and high-level documents.
"""

from typing import List, Optional, Dict, Any
from dataclasses import dataclass, field

from brain.knowledge.metadata import DocumentMetadata, ChunkMetadata


@dataclass
class ParsedSection:
    """A structured structural slice (paragraph, page, or table) of a parsed document."""
    text: str
    page_number: Optional[int] = None
    section_title: Optional[str] = None
    start_offset: int = 0
    end_offset: int = 0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ParsedDocument:
    """Output generated by a DocumentParser."""
    raw_text: str
    sections: List[ParsedSection] = field(default_factory=list)
    page_count: Optional[int] = None
    format_metadata: Dict[str, Any] = field(default_factory=dict)
    ocr_required: bool = False
    error: Optional[str] = None


@dataclass
class DocumentChunk:
    """An individual indexed chunk with text, metadata, and optional embedding vector."""
    metadata: ChunkMetadata
    text: str
    embedding: Optional[List[float]] = None

    @property
    def chunk_id(self) -> str:
        return self.metadata.chunk_id

    @property
    def document_id(self) -> str:
        return self.metadata.document_id

    def to_dict(self) -> Dict[str, Any]:
        return {
            "metadata": self.metadata.to_dict(),
            "text": self.text,
            "has_embedding": self.embedding is not None,
            "embedding_dim": len(self.embedding) if self.embedding else 0,
        }


@dataclass
class KnowledgeDocument:
    """Top-level document entity holding metadata and associated chunks."""
    metadata: DocumentMetadata
    chunks: List[DocumentChunk] = field(default_factory=list)

    @property
    def document_id(self) -> str:
        return self.metadata.document_id

    @property
    def is_ready(self) -> bool:
        from brain.knowledge.definitions import DocumentStatus
        return self.metadata.status == DocumentStatus.READY
