"""
list_desktop_files Extension - Validator
Auto-generated by Fluffy AI
"""

try:
    from action_validator import ValidationResult, SafetyLevel
except ImportError:
    from brain.action_validator import ValidationResult, SafetyLevel

class ListDesktopFilesValidator:
    """Validate list_desktop_files operations"""

    from brain.action_validator import ValidationResult, SafetyLevel

    class ListDesktopFilesValidator:
        def validate(self, command) -> ValidationResult:
            return ValidationResult(success=True, safety_level=SafetyLevel.SAFE)

def get_validator():
    return ListDesktopFilesValidator()
