"""
text_to_speech Extension - Validator
Auto-generated by Fluffy AI
"""

from action_validator import ValidationResult, SafetyLevel

class TextToSpeechValidator:
    """Validate text_to_speech operations"""
    
    def validate(self, command) -> ValidationResult:
        """Validate text_to_speech command"""
        if command.intent == Intent.TEXT_TO_SPEECH:
                    return ValidationResult(
                        is_valid=True,
                        safety_level=SafetyLevel.SAFE,
                        message="Use pyttsx3 library for text-to-speech conversion is safe"
                    )

def get_validator():
    return TextToSpeechValidator()
