"""
wifi_scan Extension - Validator
Auto-generated by Fluffy AI
"""

try:
    from brain.action_validator import ValidationResult, SafetyLevel
except ImportError:
    from action_validator import ValidationResult, SafetyLevel

class WifiScanValidator:
    """Validate wifi_scan operations"""

    from brain.action_validator import ValidationResult, SafetyLevel

    class WifiScanValidator:
        def validate(self, parameters):
            # No parameters are required for a Wi‑Fi scan action.
            return ValidationResult(is_valid=True, safety_level=SafetyLevel.SAFE)

def get_validator():
    return WifiScanValidator()
