"""
scan_wifi Extension - Validator
Auto-generated by Fluffy AI
"""

try:
    from action_validator import ValidationResult, SafetyLevel
except ImportError:
    from brain.action_validator import ValidationResult, SafetyLevel

class ScanWifiValidator:
    """Validate scan_wifi operations"""
    
    def validate(self, command: Command):
        """Validate the scan_wifi intent"""
        if command.intent.value == "SCAN_WIFI":
            return ValidationResult(is_valid=True, safety_level=SafetyLevel.SAFE, message="Safe")
        return None

def get_validator():
    return ScanWifiValidator()
