"""
bluetooth_scan Extension - Validator
Auto-generated by Fluffy AI
"""

try:
    from brain.security.action_validator import ValidationResult, SafetyLevel
except ImportError:
    try:
        from brain.action_validator import ValidationResult, SafetyLevel
    except ImportError:
        from action_validator import ValidationResult, SafetyLevel

class BluetoothScanValidator:
    """Validate bluetooth_scan operations"""

    def validate(self, command) -> ValidationResult:
        return ValidationResult(is_valid=True, safety_level=SafetyLevel.SAFE, message="Valid Bluetooth scan request.")

def get_validator():
    return BluetoothScanValidator()
