"""
test_extension Extension - Validator
Auto-generated by Fluffy AI
"""

from action_validator import ValidationResult, SafetyLevel

class TestExtensionValidator:
    """Validate test_extension operations"""
    
    def validate(self, command) -> ValidationResult:
        """Validate test_extension command"""
        return ValidationResult(
            is_valid=True,
            safety_level=SafetyLevel.SAFE,
            message="Test is safe"
        )

def get_validator():
    return TestExtensionValidator()
