"""
unknown Extension - Validator
Auto-generated by Fluffy AI
"""

from action_validator import ValidationResult, SafetyLevel

class UnknownValidator:
    """Validate unknown operations"""
    
    def validate(self, command: Command):
            """Validate unknown command"""
            if command.intent.value == "unknown":
                return ValidationResult(
                    is_valid=True,
                    safety_level=SafetyLevel.SAFE,
                    message="A script that iterates through all files in a specified folder (e.g., 'lala') and renames them based on a provided naming pattern or convention. is safe"
                )
            return None

def get_validator():
    return UnknownValidator()
