"""
list_top_processes Extension - Validator
Auto-generated by Fluffy AI
"""

try:
    from brain.action_validator import ValidationResult, SafetyLevel
except ImportError:
    from action_validator import ValidationResult, SafetyLevel

class ListTopProcessesValidator:
    """Validate list_top_processes operations"""

    from brain.action_validator import ValidationResult, SafetyLevel, ActionValidator

    class ListTopProcessesValidator(ActionValidator):
        def validate(self, parameters) -> ValidationResult:
            # No parameters expected for this action
            return ValidationResult(
                is_valid=True,
                safety_level=SafetyLevel.SAFE,
                message="Validation passed."
            )

def get_validator():
    return ListTopProcessesValidator()
