"""
compress_folder Extension - Validator
Auto-generated by Fluffy AI
"""

from action_validator import ValidationResult, SafetyLevel

class CompressFolderValidator:
    """Validate compress_folder operations"""
    
    def validate(self, command) -> ValidationResult:
        """Validate compress_folder command"""
        if command.intent == Intent.COMPRESS_FOLDER:
                    return ValidationResult(
                        is_valid=True,
                        safety_level=SafetyLevel.SAFE,
                        message="Use zipfile library to compress folder contents into a zip archive is safe"
                    )

def get_validator():
    return CompressFolderValidator()
