# Fluffy Assistant - Master Build Script
# Output: installer/FluffyAssistant_v1.0_Win64.exe
#
# PREREQUISITES:
#   Rust toolchain: https://rustup.rs
#   Node.js 18+:   https://nodejs.org
#   Python 3.11+:  https://python.org
#   Inno Setup 6:  https://jrsoftware.org/isdl.php

$ErrorActionPreference = "Stop"

$ScriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$OutputExe   = Join-Path $ScriptDir "FluffyAssistant_v1.0_Win64.exe"
$DistDir     = Join-Path $ScriptDir "dist"
$StartTime   = Get-Date

Write-Host ""
Write-Host "===========================================================" -ForegroundColor Cyan
Write-Host "   FLUFFY ASSISTANT - INSTALLER BUILD" -ForegroundColor Cyan
Write-Host "   FluffyAssistant_v1.0_Win64.exe" -ForegroundColor Cyan
Write-Host "===========================================================" -ForegroundColor Cyan
Write-Host ""

# ---- Pre-flight: Find Inno Setup ------------------------------------------
$IsscPath = $null
$Candidates = @(
    "C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
    "C:\Program Files\Inno Setup 6\ISCC.exe"
)
foreach ($p in $Candidates) {
    if (Test-Path $p) { $IsscPath = $p; break }
}
if (-not $IsscPath) {
    $cmd = Get-Command ISCC -ErrorAction SilentlyContinue
    if ($cmd) { $IsscPath = $cmd.Source }
}
if (-not $IsscPath) {
    Write-Host "  FAIL: Inno Setup 6 not found." -ForegroundColor Red
    Write-Host "  Install from: https://jrsoftware.org/isdl.php" -ForegroundColor Yellow
    exit 1
}
Write-Host "  OK: Inno Setup found: $IsscPath" -ForegroundColor Green
Write-Host ""

# Ensure dist/bin exists
New-Item -ItemType Directory -Force -Path (Join-Path $DistDir "bin") | Out-Null

# ---- Phase 1: Rust Core ---------------------------------------------------
Write-Host "[1/6] Building Rust Core..." -ForegroundColor Cyan
& (Join-Path $ScriptDir "build_core.ps1")
if ($LASTEXITCODE -ne 0) { Write-Host "FAILED: Core build." -ForegroundColor Red; exit 1 }

# ---- Phase 2: Python Brain ------------------------------------------------
Write-Host "[2/6] Building Python Brain..." -ForegroundColor Cyan
& (Join-Path $ScriptDir "build_brain.ps1")
if ($LASTEXITCODE -ne 0) { Write-Host "FAILED: Brain build." -ForegroundColor Red; exit 1 }

# ---- Phase 3: Tauri UI ----------------------------------------------------
Write-Host "[3/6] Building Tauri UI..." -ForegroundColor Cyan
& (Join-Path $ScriptDir "build_ui.ps1")
if ($LASTEXITCODE -ne 0) { Write-Host "FAILED: UI build." -ForegroundColor Red; exit 1 }

# ---- Phase 4: Launcher EXE ------------------------------------------------
Write-Host "[4/6] Building Launcher EXE (PyInstaller)..." -ForegroundColor Cyan
& (Join-Path $ScriptDir "build_launcher.ps1")
if ($LASTEXITCODE -ne 0) { Write-Host "FAILED: Launcher build." -ForegroundColor Red; exit 1 }

# ---- Phase 5: Copy scripts + prepare .env ---------------------------------
Write-Host "[5/6] Copying launcher scripts and preparing .env..." -ForegroundColor Cyan

$LauncherSrc  = Join-Path $ScriptDir "launcher"
$LauncherDist = Join-Path $DistDir "launcher"
if (Test-Path $LauncherSrc) {
    if (Test-Path $LauncherDist) {
        Remove-Item $LauncherDist -Recurse -Force
    }
    robocopy $LauncherSrc $LauncherDist /E /NFL /NDL /NJH /NJS | Out-Null
    Write-Host "  OK: Launcher scripts copied to dist\launcher\" -ForegroundColor Green
}

$EnvSrc  = Join-Path $ProjectRoot ".env"
$EnvDist = Join-Path $DistDir ".env"
if (Test-Path $EnvSrc) {
    Copy-Item -Path $EnvSrc -Destination $EnvDist -Force
    $txt = Get-Content $EnvDist -Raw
    $txt = $txt -replace 'FLUFFY_TOKEN=.*', '# FLUFFY_TOKEN=<auto-generated on first run>'
    $txt = $txt -replace 'PYTHON_PATH=.*', 'PYTHON_PATH=./python/python.exe'
    Set-Content -Path $EnvDist -Value $txt
    Write-Host "  OK: .env prepared for installer." -ForegroundColor Green
}

# ---- Phase 6: Compile Inno Setup ------------------------------------------
Write-Host "[6/6] Compiling Inno Setup installer..." -ForegroundColor Cyan

$IssFile = Join-Path $ScriptDir "fluffy_setup.iss"
if (-not (Test-Path $IssFile)) {
    Write-Host "  FAIL: fluffy_setup.iss not found!" -ForegroundColor Red
    exit 1
}

& $IsscPath $IssFile
if ($LASTEXITCODE -ne 0) {
    Write-Host "  FAIL: Inno Setup compilation failed." -ForegroundColor Red
    exit 1
}

# ---- Summary --------------------------------------------------------------
$Elapsed = (Get-Date) - $StartTime
$Min = [math]::Floor($Elapsed.TotalMinutes)
$Sec = $Elapsed.Seconds

Write-Host ""
Write-Host "===========================================================" -ForegroundColor Green
Write-Host "  BUILD COMPLETE" -ForegroundColor Green
if (Test-Path $OutputExe) {
    $MB = [math]::Round((Get-Item $OutputExe).Length / 1MB, 1)
    Write-Host "  Output: FluffyAssistant_v1.0_Win64.exe ($MB MB)" -ForegroundColor Green
}
Write-Host "  Time:   ${Min}m ${Sec}s" -ForegroundColor Green
Write-Host "===========================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Ready to distribute!" -ForegroundColor Cyan